### ISSUE TITLE
synchronization issue

### ISSUE THREAD

**Issue by Deathay** [RefractorGSCM/Refractor#36] opened 2021-11-15 20:12 UTC
Hey, when banning a person in synchronization the ban will only start to work if you joined the server once, then the command has been sent so the time will never be right if you run for example multiple servers, if you get banned for 2 weeks and join the other server next week means that you'll get banned on that different server for 2 weeks meanwhile there is one week left in the panel (the server where you joined week earlier). Also unbanning in synchronization does not work, only for the server you selected but if you did not join that server when the ban was active(on the panel) you will never be banned on any other servers because you never joined them, sync ban only sends the command when you join the server, then you'll be banned. Mute works fine in synchronization, but unmute command does not work on other servers, only the only who was selected. quiete hard to explain, hopefully this was understandable :D

**Comment by Deathay** [comment] 2021-11-15 20:22
when you select the right server it instantly does the punishment btw, i talk about the other servers which does not

**Comment by sniddunc** [comment] 2021-11-15 21:05
Most of this is probably caused by the infraction commands only being executed on the selected server when being created. When they join another server, the infractions are then synchronized.

The duration thing you mentioned is likely a bug, though. It should be replacing {{DURATION}} with the remaining time when synchronizing rather than the duration the infraction was created with. This will also require an implementation of some kind of command queue to retain commands for later if a server is currently unavailable.

**Comment by sniddunc** [comment] 2021-11-15 22:51
@Deathay I wasn't able to replicate the infraction sync duration issue you mentioned.

I did the following to attempt to replicate it:
1. Banned myself for 10 minutes
2. Waited 2 minutes
3. Joined a different server
4. The server synced the ban and banned me for 8 minutes instead of the initial 10 minutes

Based on what you said above, it should've re-banned me for 10 minutes even though there were only 8 minutes left. Can you confirm that this is what you're experiencing?

**Comment by Deathay** [comment] 2021-11-16 07:06
> @Deathay I wasn't able to replicate the infraction sync duration issue you mentioned.
> 
> I did the following to attempt to replicate it:
> 
> 1. Banned myself for 10 minutes
> 2. Waited 2 minutes
> 3. Joined a different server
> 4. The server synced the ban and banned me for 8 minutes instead of the initial 10 minutes
> 
> Based on what you said above, it should've re-banned me for 10 minutes even though there were only 8 minutes left. Can you confirm that this is what you're experiencing?

Correct that is what i’ve been experiencing as well the unban/unmute does not work, i will update Refractor to the latest version and retry again.

**Comment by sniddunc** [comment] 2021-11-17 00:57
Fixed in pre-release branch v0.4.0

**Closed by sniddunc** 2021-11-17 00:57 UTC
Labels: bug
